[pytest]

markers =
    auth: tests hitting the auth/ping endpoints
    positive: happy-path scenarios
    crud: CRUD operations 
    smoke: tests for smoke test runs
    health: test for a healthcheck
    negative: negative test cases

addopts = -v
testpaths = tests 